name: ci

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:
  schedule:
    - cron: "0 5 * * *"

jobs:
  build:
    strategy:
      fail-fast: false

      matrix:
        os:
          - ubuntu-latest
          - macos-latest
        ocaml-compiler:
          - ocaml-variants.5.6.0+trunk
          - 5.5.x
          - 5.4.x
          - 5.3.x
          - 5.2.x
          - 5.1.x
          - 5.0.x
          - 4.14.x
          - 4.13.x
          - 4.12.x

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v7
        with:
          lfs: true # https://github.com/ocaml/setup-ocaml/issues/895#issuecomment-2477062336

      - name: Set up OCaml ${{ matrix.ocaml-compiler }}
        uses: ocaml/setup-ocaml@v3
        with:
          ocaml-compiler: ${{ matrix.ocaml-compiler }}

      - name: Pin dependencies
        if: ${{ matrix.ocaml-compiler == 'ocaml-variants.5.6.0+trunk' }}
        run: opam pin add ppxlib git+https://github.com/ocaml-ppx/ppxlib.git#377fee7793ee12d82772c619efee7985ea31f53f

      - name: Install dependencies
        run: opam install . --deps-only

      - name: Build
        run: opam exec -- dune build
